apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-sample
  template:
    metadata:
      labels:
        app: rust-sample
    spec:
      containers:
      - name: rust-sample
        image: minikube-local-registry:5000/rust-sample:latest
        ports:
        - containerPort: 8080
