name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    name: Setup Rust Environment
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Setup Rust environment
      uses: mehmet-copur/rust-pipeline/actions/rust/setup@main

  build-project:
    name: Build Project
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Build the Rust project
      uses: mehmet-copur/rust-pipeline/actions/rust/build@main

  unit-test-project:
    name: Running Unit Tests
    needs: build-project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Test units for the Rust project
      uses: mehmet-copur/rust-pipeline/actions/rust/test/unit@main

  integration-test-project:
    name: Running Integration Tests
    needs: build-project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Test integrations for the Rust project
      uses: mehmet-copur/rust-pipeline/actions/rust/test/integration@main      

  e2e-test-project:
    name: Running E2E Tests
    needs: build-project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Test E2E for the Rust project
      uses: mehmet-copur/rust-pipeline/actions/rust/test/integration@main   

  docker-build-and-push:
    name: Docker Build and Push
    needs: test-project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Build and Push Docker image
      uses: mehmet-copur/rust-pipeline/actions/docker/build-and-push@main
      with:
        dockerfile: "./Dockerfile"
        image-name: "rust-sample-rust-app"
        image-tag: ${{ github.sha }}
        registry-url: "docker.io"
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy to Kubernetes
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}

    - name: Deploy to Kubernetes
      uses: mehmet-copur/rust-pipeline/.github/actions/kubernetes/deploy@main
      with:
        kubeconfig-data: ${{ secrets.KUBECONFIG_DATA }}
        manifest-path: "./k8s/"
