name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Setup Rust environment
      uses: mehmet-copur/rust-pipeline/actions/rust/setup@main

    - name: Build the Rust project
      uses: mehmet-copur/rust-pipeline/actions/rust/build@main

    - name: Test the Rust project
      uses: mehmet-copur/rust-pipeline/actions/rust/test/unit@main

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Build and Push Docker image
      uses: mehmet-copur/rust-pipeline/actions/docker/build-and-push@main
      with:
        dockerfile: "./Dockerfile"
        image-name: "rust-sample-rust-app"
        image-tag: ${{ github.sha }}
        registry-url: "docker.io"
        registry-username: ${{ secrets.DOCKER_USERNAME }}
        registry-password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Deploy to Kubernetes
      uses: mehmet-copur/rust-pipeline/.github/actions/kubernetes/deploy@main
      with:
        kubeconfig-data: ${{ secrets.KUBECONFIG_DATA }}
        manifest-path: "./k8s/"
